spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/restaurant-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    encoding: UTF-8