spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/restaurant-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    encoding: UTF-8
custom:
  jwt:
    secret: ${JWT_SECRET:changeMeToAStrongSecret}
    expiration: ${JWT_EXPIRATION:3600} # 60 minutos
    issuer: ${JWT_ISSUER:Restaurant Project API}
springdoc:
  swagger-ui:
    path: swagger-ui.html